In [1]:
import pandas as pd
import numpy as np
import sqlite3 as sql
data=pd.read_csv('processed_data/demography_module_2.csv',index_col=0)
data

,population,area,population_density,sex_ratio,literacy,total_workers,non_workers,WPR
district_name,,,,,,,,
Central,582320,21,27729.523810,892,85.14,207374,374946,35.611691
East,1709346,63,27132.476190,884,89.31,579692,1129654,33.913087
New Delhi,142004,35,4057.257143,822,88.34,59541,82463,41.929101
North,887978,61,14557.016393,869,86.85,296446,591532,33.384386
North East,2241624,62,36155.225806,886,83.12,655398,1564699,29.237642
North West,3656539,443,8254.038375,865,84.74,1121005,2321536,30.657543
South,2731929,247,11060.441296,862,86.57,924393,1807536,33.836641
South West,2292958,421,5446.456057,840,88.28,795352,1497606,34.686723
West,2543243,130,19563.407692,875,86.98,874320,1668923,34.378154

In [12]:
data['population_density']=data['population']/data['area']
data['WPR']=(data['total_workers']/data['population'])*100
data

,population,area,population_density,sex_ratio,literacy,total_workers,non_workers,WPR
district_name,,,,,,,,
Central,582320,21,27729.523810,892,85.14,207374,374946,35.611691
East,1709346,63,27132.476190,884,89.31,579692,1129654,33.913087
New Delhi,142004,35,4057.257143,822,88.34,59541,82463,41.929101
North,887978,61,14557.016393,869,86.85,296446,591532,33.384386
North East,2241624,62,36155.225806,886,83.12,655398,1564699,29.237642
North West,3656539,443,8254.038375,865,84.74,1121005,2321536,30.657543
South,2731929,247,11060.441296,862,86.57,924393,1807536,33.836641
South West,2292958,421,5446.456057,840,88.28,795352,1497606,34.686723
West,2543243,130,19563.407692,875,86.98,874320,1668923,34.378154

In [13]:
data.to_csv('demography_module_2.csv',index=True)

## Worker Participation Rate

**WPR**= (**Total Workers**/**Total population**)*100